language: julia
os:
  - osx
julia:
  - 1.1
notifications:
  email: false

jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: osx
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
after_success: skip
